name: CI

on:
 push:
   branches:
   - main
   paths-ignore:
   - 'README.md'
   - 'helm/**'

jobs:
   
   build:
     runs-on: ubuntu-latest

     steps:
     - name: checkout repository
       uses: actions/checkout@v4

     - name: set up go 1.22
       uses: actions/setup-go@v2
       with:
         go-version: 1.22

     - name: build
       run: go build -o go-web-app

     - name: test
       run: go test ./...
    

   code-quality:
     runs-on: ubuntu-latest
     needs: build

     steps:
     - name: checkout repository
       uses: actions/checkout@v4

     - name: run golangci-lint
       uses: golangci/golangci-lint-action@v6
       with:
         version: v1.62.0

   push:
     runs-on: ubuntu-latest
     needs: [build, code-quality]

     steps:
     - name: checkout repository
       uses: actions/checkout@v4

     - name: setup docker buildx
       uses: docker/setup-buildx-action@v3

     - name: login to Dockerhub
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name : build and push action
       uses: docker/build-push-action@v6
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}
        
   update-newtag-in-helm-chart:
     runs-on: ubuntu-latest
     
     needs: [push] 
     
     steps:
     - name: checkout repository
       uses: actions/checkout@v4
       with:
        token: ${{ secrets.TOKEN }}

     - name: update tag in helm chart
       run: |
          sed -i'' -e 's/tag: .*/tag: "${{ github.run_id }}"/' go-web-app/go-web-app-chart/values.yaml
       
     - name: commitand push the changes
       run: |
        git config --global user.email "shrgacche@gmail.com"
        git config --global user.name "shr1324"
        git add go-web-app/go-web-app-chart/values.yaml
        git diff --cached --quiet || git commit -m "update tag ${{ github.run_id }} in helm chart"
        git commit -m "update tag ${{ github.run_id }} in helm chart"
        git push

           
         
            
